Update push-to-main.yml

diff --git a/.github/workflows/push-to-main.yml b/.github/workflows/push-to-main.yml
--- a/.github/workflows/push-to-main.yml
+++ b/.github/workflows/push-to-main.yml
@@ -19,8 +19,10 @@ jobs:
     - name: Install Docker
       run: |
         brew install docker
-        brew install colima
-        start colima
+        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+        open -a /Applications/Docker.app --args --unattended --accept-license
+        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
         
 
     # build docker image
